filenameauto/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.static import serve

from filenameauto import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nameauto/', include('name_generate.urls')),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('', RedirectView.as_view(pattern_name='NameGenerate'), name='home'),
]

name_generate/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.NameGenerateView.as_view(), name='NameGenerate'),
    path('techn/<int:pk>', views.TechnicalListView.as_view(), name='Technical'),
    path('plan/<int:pk>', views.PlanListView.as_view(), name='Plan'),
    path('record/<int:pk>', views.RecordListView.as_view(), name='Record'),
    path('ajax/load_scheme_module', views.load_scheme_module, name='ajax_load_scheme_module'),
    path('ajax/ajax_generate_tfname', views.generate_technical_file_name, name='ajax_generate_tfname'),
    path('ajax/ajax_generate_pfname', views.generate_plan_file_name, name='ajax_generate_pfname'),
    path('ajax/ajax_generate_rfname', views.generate_record_file_name, name='ajax_generate_rfname'),
]

name_generate/models.py
from datetime import timezone

from django.db import models


# Create your models here.
class FlieClass(models.Model):
    name = models.CharField(max_length=30, verbose_name="文件类型")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '文件分类'


class ProjectFlieClass(models.Model):
    name = models.CharField(max_length=30, verbose_name="项目文件类型")
    flieclass = models.ForeignKey(FlieClass, on_delete=models.CASCADE)
    code = models.CharField(max_length=30, null=True, blank=True, verbose_name="代号")

    def __str__(self):
        return self.code

    class Meta:
        verbose_name_plural = '项目分类'


class Project(models.Model):
    name = models.CharField(max_length=30, verbose_name="项目名")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '项目列表'


class Scheme(models.Model):
    name = models.CharField(max_length=30, verbose_name="方案名")
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name="项目")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '方案表'


class Module(models.Model):
    name = models.CharField(max_length=30, verbose_name="模块名")
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name="项目")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '模块表'


class TechniFileName(models.Model):
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, verbose_name="项目")
    projectflieclass = models.ForeignKey(ProjectFlieClass, on_delete=models.SET_NULL, null=True, verbose_name="类别代号")

    scheme = models.ForeignKey(Scheme, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="方案")
    module = models.ForeignKey(Module, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="模块")
    name = models.CharField(max_length=30, verbose_name="文件名")
    date = models.DateField(null=True, blank=True, verbose_name="日期")
    author = models.CharField(max_length=30, null=True, blank=True, verbose_name="作者")
    number = models.IntegerField(null=True, blank=True, verbose_name="序号")
    version = models.CharField(max_length=30, null=True, blank=True, verbose_name="版本")
    result = models.CharField(max_length=50, null=False, verbose_name="文件编号")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '技术类文件'


phase_CHOICES = [
    ('01', '1'),
    ('02', '2'),
    ('03', '3'),
    ('04', '4'),
    ('05', '5'),
    ('06', '6'),
    ('07', '7'),
    ('08', '8'),
    ('09', '9'),
    ('10', '10'),
]


class PlanFileName(models.Model):
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, verbose_name="项目")
    projectflieclass = models.ForeignKey(ProjectFlieClass, on_delete=models.SET_NULL, null=True, verbose_name="类别代号")
    phase = models.CharField(null=True, max_length=30, blank=True, verbose_name="阶段", choices=phase_CHOICES)
    date = models.DateField(null=True, blank=True, verbose_name="日期")
    name = models.CharField(max_length=30, verbose_name="文件名")
    author = models.CharField(max_length=30, null=True, blank=True, verbose_name="作者")
    number = models.IntegerField(null=True, blank=True, verbose_name="序号")
    result = models.CharField(max_length=60, null=True, verbose_name="文件编号")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '计划类文件'


class RecordFileName(models.Model):
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, verbose_name="项目")
    projectflieclass = models.ForeignKey(ProjectFlieClass, on_delete=models.SET_NULL, null=True, verbose_name="类别代号")
    date = models.DateField(null=True, blank=True, verbose_name="日期")
    name = models.CharField(max_length=30, verbose_name="文件名")
    author = models.CharField(max_length=30, null=True, blank=True, verbose_name="作者")
    number = models.IntegerField(null=True, blank=True, verbose_name="序号")
    result = models.CharField(max_length=60, null=True, verbose_name="文件编号")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '记录类文件'


class ImportFile(models.Model):
    file = models.FileField(upload_to='static', verbose_name=u'请上传正确格式excel文件')
    name = models.CharField(max_length=50, verbose_name=u'文件名')
    datetime = models.DateTimeField(null=True, blank=True, verbose_name="时间", auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

name_generate/forms.py
from django import forms
from .models import *


class BaseForm(forms.ModelForm):
    class Meta:
        model = TechniFileName

        fields = ('project', 'scheme', 'module', 'name', 'date', 'author')
        widgets = {

        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class TechnicalForm(forms.ModelForm):
    class Meta:
        model = TechniFileName
        fields = (
            'project', 'scheme', 'module', 'name', 'date', 'author', 'version', 'number', 'result', 'projectflieclass')

        widgets = {
            'project': forms.Select(),
            'projectflieclass': forms.Select(attrs={'style': "display:none;"}),
            'scheme': forms.Select(),
            'module': forms.Select(),
            'name': forms.TextInput(attrs={'placeholder': '请输入文件名称', 'value': ''}),
            'date': forms.DateInput(attrs={'type': 'date'}),
            'author': forms.TextInput(),
            'version': forms.TextInput(attrs={'style': "display:none;"}),
            'number': forms.TextInput(attrs={'style': "display:none;"}),
            'result': forms.TextInput(attrs={'style': "border:none;cursor:text", 'readonly': 'true'}),
        }

    def __init__(self, *args, **kwargs):
        pkProjectClass = int(kwargs.pop('ProjectClass'))
        print(pkProjectClass)
        super().__init__(*args, **kwargs)
        self.fields['scheme'].queryset = Scheme.objects.none()
        self.fields['module'].queryset = Module.objects.none()
        self.fields['project'].queryset = Project.objects.all().order_by('name')

        if 'project' in self.data:
            try:
                project_id = int(self.data.get('project'))
                self.fields['scheme'].queryset = Scheme.objects.filter(project_id=project_id).order_by('name')
                self.fields['module'].queryset = Module.objects.filter(project_id=project_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['scheme'].queryset = self.instance.project.scheme_set.order_by('name')
            self.fields['module'].queryset = self.instance.project.module_set.order_by('name')


class PlanForm(forms.ModelForm):
    class Meta:
        model = PlanFileName
        fields = ('project', 'projectflieclass', 'phase', 'date', 'name', 'author', 'number', 'result')
        widgets = {
            'project': forms.Select(),
            'projectflieclass': forms.Select(attrs={'style': "display:none;"}),
            'phase': forms.Select(),
            'date': forms.DateInput(attrs={'type': 'date'}),
            'name': forms.TextInput(attrs={'placeholder': '请输入文件名称', 'value': ''}),
            'author': forms.TextInput(),
            'number': forms.TextInput(attrs={'style': "display:none;"}),
            'result': forms.TextInput(attrs={'style': "border:none;cursor:text", 'readonly': 'true'}),
        }

    def __init__(self, *args, **kwargs):
        pkProjectClass = int(kwargs.pop('ProjectClass'))
        print(pkProjectClass)
        super().__init__(*args, **kwargs)
        self.fields['project'].queryset = Project.objects.all().order_by('name')



class RecordForm(forms.ModelForm):
    class Meta:
        model = RecordFileName
        fields = ('project', 'date', 'name', 'author', 'number', 'result', 'projectflieclass')
        widgets = {
            'project': forms.Select(),
            'projectflieclass': forms.Select(attrs={'style': "display:none;"}),
            'date': forms.DateInput(attrs={'type': 'date'}),
            'name': forms.TextInput(attrs={'placeholder': '请输入文件名称', 'value': ''}),
            'author': forms.TextInput(),
            'number': forms.TextInput(attrs={'style': "display:none;"}),
            'result': forms.TextInput(attrs={'style': "border:none;cursor:text", 'readonly': 'true'}),
        }

    def __init__(self, *args, **kwargs):
        pkProjectClass = int(kwargs.pop('ProjectClass'))
        print(pkProjectClass)
        super().__init__(*args, **kwargs)
        self.fields['project'].queryset = Project.objects.all().order_by('name')

name_generate/views.py
from django.shortcuts import render, HttpResponse
import json
# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, CreateView

from name_generate.forms import BaseForm, TechnicalForm, PlanForm, RecordForm
from name_generate.models import ProjectFlieClass, FlieClass, TechniFileName, Scheme, Module
from name_generate.FileNameAuto import TechnicalFileNameAuto, PlanFileNameAuto, RecordFileNameAuto


class NameGenerateView(CreateView):
    model = FlieClass  # 关联的数据表
    form_class = BaseForm  # 关联的表单类
    template_name = 'name_generate/base_view.html'  # 模板路径
    success_url = reverse_lazy('NameGenerate')  # 表单提交后跳转url

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tech'] = FlieClass.objects.get(name='技术类文件').projectflieclass_set.all()
        context['plan'] = FlieClass.objects.get(name='计划类文件').projectflieclass_set.all()
        context['record'] = FlieClass.objects.get(name='记录类文件').projectflieclass_set.all()
        return context


class TechnicalListView(NameGenerateView):
    template_name = 'name_generate/Technical.html'
    form_class = TechnicalForm

    model = ProjectFlieClass

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projectclass'] = ProjectFlieClass.objects.get(pk=self.get_pk())
        return context

    def get_pk(self):
        path = str(self.request.path)
        pos = path.rfind('/')
        if pos != -1:
            return path[pos + 1:]
        else:
            raise Exception('get_pk 不是正确的路径,获取不到数据库对象')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        kwargs.update({
            'ProjectClass': self.get_pk()
        })
        return kwargs


class PlanListView(NameGenerateView):
    template_name = 'name_generate/plan.html'
    form_class = PlanForm

    model = ProjectFlieClass

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projectclass'] = ProjectFlieClass.objects.get(pk=self.get_pk())
        return context

    def get_pk(self):
        path = str(self.request.path)
        pos = path.rfind('/')
        if pos != -1:
            return path[pos + 1:]
        else:
            raise Exception('get_pk 不是正确的路径,获取不到数据库对象')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        kwargs.update({
            'ProjectClass': self.get_pk()
        })
        return kwargs


class RecordListView(NameGenerateView):
    template_name = 'name_generate/Record.html'
    form_class = RecordForm

    model = ProjectFlieClass

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projectclass'] = ProjectFlieClass.objects.get(pk=self.get_pk())
        return context

    def get_pk(self):
        path = str(self.request.path)
        pos = path.rfind('/')
        if pos != -1:
            return path[pos + 1:]
        else:
            raise Exception('get_pk 不是正确的路径,获取不到数据库对象')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        kwargs.update({
            'ProjectClass': self.get_pk()
        })
        return kwargs


def load_scheme_module(request):
    project_id = request.GET.get('project')
    schemes = Scheme.objects.filter(project_id=project_id).order_by('name')
    modules = Module.objects.filter(project_id=project_id).order_by('name')
    return render(request, 'name_generate/scheme_module_list_option.html', {'schemes': schemes, 'modules': modules})


def generate_technical_file_name(request):
    if request.method == "POST" and request.POST:
        validData = TechnicalForm(request.POST)
        if validData.is_valid():
            print("is_valid")
        else:
            print(validData.errors)

    technicalFileName = TechnicalFileNameAuto(project=request.GET.get('project'),
                                              projectflieclass=request.GET.get('projectflieclass'),
                                              scheme=request.GET.get('scheme'),
                                              module=request.GET.get('module'),
                                              name=request.GET.get('name'),
                                              date=request.GET.get('date'),
                                              author=request.GET.get('author'),
                                              version=request.GET.get('version'))
    result = technicalFileName.getFileName()
    data = [{'number': technicalFileName.number, 'version': technicalFileName.version, 'result': result}]
    ret = json.dumps(data)
    return HttpResponse(ret)


def generate_plan_file_name(request):
    if request.method == "POST" and request.POST:
        validData = PlanForm(request.POST)
        if validData.is_valid():
            print("is_valid")
        else:
            print(validData.errors)

    planFileName = PlanFileNameAuto(project=request.GET.get('project'),
                                    projectflieclass=request.GET.get('projectflieclass'),
                                    phase=request.GET.get('phase'),
                                    name=request.GET.get('name'),
                                    date=request.GET.get('date'),
                                    author=request.GET.get('author'),
                                    )
    result = planFileName.getFileName()
    data = [{'number': planFileName.number, 'result': result}]
    ret = json.dumps(data)
    return HttpResponse(ret)


def generate_record_file_name(request):
    if request.method == "POST" and request.POST:
        validData = RecordForm(request.POST)
        if validData.is_valid():
            print("is_valid")
        else:
            print(validData.errors)

    planFileName = RecordFileNameAuto(project=request.GET.get('project'),
                                      projectflieclass=request.GET.get('projectflieclass'),
                                      name=request.GET.get('name'),
                                      date=request.GET.get('date'),
                                      author=request.GET.get('author'),
                                      )
    result = planFileName.getFileName()
    data = [{'number': planFileName.number, 'result': result}]
    ret = json.dumps(data)
    return HttpResponse(ret)

name_generate/templates/name_generate/Record.html
{% extends 'name_generate/base_view.html' %}
{% block technic_class  %}"nav nav-list collapse"{% endblock %}
{% block plan_class  %}"nav nav-list collapse"{% endblock %}
{% block record_class  %}"nav nav-list collapse in"{% endblock %}
{% block page_title %}
    {{ projectclass.name }}
    <input type="text" name="pc" style="display:none;" maxlength="30" id="id_pc" value="{{ projectclass.pk }}">
{% endblock %}


{% block form_com %}
    <form method="post"  id="TechnicalForm" data-schememodule-url="{% url 'ajax_load_scheme_module' %}" data-generate-url="{% url 'ajax_generate_rfname' %}"onsubmit="return commit()" >
        {% csrf_token %}
          <label for="ProjectName">项目名称</label>
          {{ form.project }}
          <label>日期（选填）</label>
           {{ form.date }}
          <label>文件名称</label>
           {{ form.name }}
          <label>作者（选填）</label>
           {{ form.author }}
          <label></label>
          <label></label>
          <input name="Creat" type="button" id="click" value="生成文件全名">
          <label></label>
          {{ form.result }}
          {{ form.number }}
          {{ form.projectflieclass }}
          <label></label>
          <label></label>
          <input class="btn btn-danger"  type="submit" value="确认使用文件编号"/>
        </form>
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script  type="text/javascript">

          var ddd = new Date();
          var day =ddd.getDate();
          var month = ddd.getMonth()+1; 
          if(ddd.getMonth() < 9){
                month = "0"+(ddd.getMonth()+1); 
          }
          if(ddd.getDate()<10){
               day = "0"+ddd.getDate(); 
          }
          var datew = ddd.getFullYear()+"-"+month+"-"+day;
          var datew = datew.toString();

          $("#id_date").val(datew);

      function commit()
      {
         var result =  $("#id_result").val();

         if(result == '')
         {
             alert("请先点击生成");
             return false;
         }
          if(confirm("您确定使用该文件编号并将其存入数据库吗? 确认后将跳转到主页")){
             alert("该命名已提交到数据库");
          }
          else{
              alert("您取消了提交");
              return false;
          }
          return true;

      }


        $("#click").click(function () {
             var url = $("#TechnicalForm").attr("data-generate-url");
             var id_project =  $("#id_project").val();
             $("#id_projectflieclass").val($("#id_pc").val());
             var id_projectflieclass =  $("#id_projectflieclass").val();
             var id_name =  $("#id_name").val();
             var id_date =  $("#id_date").val();
             var id_author =  $("#id_author").val();
             if (id_project == ''){
                 window.alert("请选择项目");
                 return;
             }

             if (id_name == '请输入文件名称'||id_name == ''){
                 window.alert("请输入文件名称");
                 return;
             }
          $.ajax({
            url: url,
            data: {
                'project': id_project,
                'projectflieclass': id_projectflieclass,
                'name': id_name,
                'date': id_date,
                'author': id_author,
            },
            success: function (data) {
                var obj = JSON.parse(data);
                $("#id_result").val(obj[0].result)
                $("#id_number").val(obj[0].number)
            }
          });
        });
      </script>
{% endblock %}

name_generate/templates/name_generate/Technical.html
{% extends 'name_generate/base_view.html' %}

{% block page_title %}
    {{ projectclass.name }}
    <input type="text" name="pc" style="display:none;" maxlength="30" id="id_pc" value="{{ projectclass.pk }}">
{% endblock %}


{% block form_com %}
    <form method="post"  id="TechnicalForm" data-schememodule-url="{% url 'ajax_load_scheme_module' %}" data-generate-url="{% url 'ajax_generate_tfname' %}" onsubmit="return commit()">
        {% csrf_token %}
          <label for="ProjectName">项目名称</label>
          {{ form.project }}
          <label for="SchemeName">方案名（选填）</label>
          {{ form.scheme }}
          <label for="ModuleName">模块名（选填）</label>
          {{ form.module }}
          <label>文件名称</label>
           {{ form.name }}
          <label>日期（选填）</label>
           {{ form.date }}
          <label>作者（选填）</label>
           {{ form.author }}

          <label>版本</label>
        <select name="version" id="version">
            <option value="debug" selected>评审</option>
            <option value="release" >发布</option>
        </select>
          <label></label>
          <input name="Creat" type="button" id="click" value="生成文件全名">
          <label></label>
          {{ form.result }}
          {{ form.version }}
          {{ form.projectflieclass }}
          {{ form.number }}
          <label></label>
          <label></label>
          <input class="btn btn-danger"  type="submit" value="确认使用文件编号"/>
        </form>
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script  type="text/javascript">
          var ddd = new Date();
          var day =ddd.getDate();
          var month = ddd.getMonth()+1; 
          if(ddd.getMonth() < 9){
                month = "0"+(ddd.getMonth()+1); 
          }
          if(ddd.getDate()<10){
               day = "0"+ddd.getDate(); 
          }
          var datew = ddd.getFullYear()+"-"+month+"-"+day;
          var datew = datew.toString();

          $("#id_date").val(datew);

      function commit()
      {
         var result =  $("#id_result").val();

         if(result == '')
         {
             alert("请先点击生成文件编号");
             return false;
         }
          if(confirm("您确定使用该文件编号并将其存入数据库吗? 确认后将跳转到主页")){
             alert("该命名已提交到数据库");
          }
          else{
              alert("您取消了提交");
              return false;
          }
          return true;

      }

        $("#id_project").change(function () {
          var url = $("#TechnicalForm").attr("data-schememodule-url");
          var id_project = $(this).val();

          $.ajax({
            url: url,
            data: {
              'project': id_project
            },
            success: function (data) {
                var res = data.split('splite')
                $("#id_scheme").html(res[0]);
                $("#id_module").html(res[1]);
            }
          });
        });

        $("#click").click(function () {
             var url = $("#TechnicalForm").attr("data-generate-url");
             var id_project =  $("#id_project").val();
             $("#id_projectflieclass").val($("#id_pc").val());
             var id_projectflieclass =  $("#id_projectflieclass").val();
             var id_scheme =  $("#id_scheme").val();
             var id_module =  $("#id_module").val();
             var id_name =  $("#id_name").val();
             var id_date =  $("#id_date").val();
             var id_author =  $("#id_author").val();
             var version =  $("#version").val();
             if (id_project == ''){
                 window.alert("请选择项目");
                 return;
             }

             if (id_name == '请输入文件名称'||id_name == ''){
                 window.alert("请输入文件名称");
                 return;
             }

          $.ajax({
            url: url,
            data: {
                'project': id_project,
                'projectflieclass':id_projectflieclass,
                'scheme': id_scheme,
                'module': id_module,
                'name': id_name,
                'date': id_date,
                'author': id_author,
                'version':version,
            },
            success: function (data) {
                var obj = JSON.parse(data);
                $("#id_result").val(obj[0].result)
                $("#id_version").val(obj[0].version)
                $("#id_number").val(obj[0].number)
            }
          });
        });

      </script>
{% endblock %}

name_generate/templates/name_generate/base_view.html
{% extends 'base.html' %}


{% block technical_list %}
    {% for obj in tech %}
        <li ><a href="{% url 'Technical' obj.pk %}">{{ obj.name }}</a></li>
    {% endfor %}
{% endblock %}

{% block plan_list %}
    {% for obj in plan %}
        <li ><a href="{% url 'Plan' obj.pk %}">{{ obj.name }}</a></li>
    {% endfor %}
{% endblock %}

{% block record_list %}
    {% for obj in record %}
        <li ><a href="{% url 'Record' obj.pk %}">{{ obj.name }}</a></li>
    {% endfor %}
{% endblock %}

name_generate/templates/name_generate/plan.html
{% extends 'name_generate/base_view.html' %}
{% block technic_class  %}"nav nav-list collapse"{% endblock %}
{% block plan_class  %}"nav nav-list collapse in"{% endblock %}
{% block record_class  %}"nav nav-list collapse"{% endblock %}
{% block page_title %}
    {{ projectclass.name }}
    <input type="text" name="pc" style="display:none;" maxlength="30" id="id_pc" value="{{ projectclass.pk }}">
{% endblock %}


{% block form_com %}
    <form method="post"  id="TechnicalForm" data-schememodule-url="{% url 'ajax_load_scheme_module' %}" data-generate-url="{% url 'ajax_generate_pfname' %}" onsubmit="return commit()">
        {% csrf_token %}
          <label for="ProjectName">项目名称</label>
          {{ form.project }}
          <label for="Phase">项目阶段</label>
          {{ form.phase }}
          <label>日期（选填）</label>
           {{ form.date }}
        <label>文件名称</label>
           {{ form.name }}
          <label>作者（选填）</label>
           {{ form.author }}
          <label></label>
          <label></label>
          <input name="Creat" type="button" id="click" value="生成文件全名">
          <label></label>
          {{ form.result }}
          {{ form.projectflieclass }}
          {{ form.number }}
          <label></label>
          <label></label>
          <input class="btn btn-danger"  type="submit" value="确认使用文件编号"/>
        </form>
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
       <script  type="text/javascript">
          var ddd = new Date();
          var day =ddd.getDate();
          var month = ddd.getMonth()+1; 
          if(ddd.getMonth() < 9){
                month = "0"+(ddd.getMonth()+1); 
          }
          if(ddd.getDate()<10){
               day = "0"+ddd.getDate(); 
          }
          var datew = ddd.getFullYear()+"-"+month+"-"+day;
          var datew = datew.toString();
          $("#id_date").val(datew);

      function commit()
      {
         var result =  $("#id_result").val();

         if(result == '')
         {
             alert("请先点击生成");
             return false;
         }
          if(confirm("您确定使用该文件编号并将其存入数据库吗? 确认后将跳转到主页")){
             alert("该命名已提交到数据库");
          }
          else{
              alert("您取消了提交");
              return false;
          }
          return true;

      }


        $("#click").click(function () {
             var url = $("#TechnicalForm").attr("data-generate-url");

             var id_project =  $("#id_project").val();
             $("#id_projectflieclass").val($("#id_pc").val());
             var id_projectflieclass =  $("#id_projectflieclass").val();
             var id_phase =  $("#id_phase").val();
             var id_name =  $("#id_name").val();
             var id_date =  $("#id_date").val();
             var id_author =  $("#id_author").val();
             if (id_project == ''){
                 window.alert("请选择项目");
                 return;
             }

             if (id_name == '请输入文件名称'||id_name == ''){
                 window.alert("请输入文件名称");
                 return;
             }
          $.ajax({
            url: url,
            data: {
                'project': id_project,
                'projectflieclass': id_projectflieclass,
                'phase': id_phase,
                'name': id_name,
                'date': id_date,
                'author': id_author,
            },
            success: function (data) {
                var obj = JSON.parse(data);
                $("#id_result").val(obj[0].result)
                $("#id_number").val(obj[0].number)
            }
          });
        });

      </script>
{% endblock %}

name_generate/templates/name_generate/scheme_module_list_option.html
<option value="">---------</option>
{% for scheme in schemes %}
<option value="{{ scheme.pk }}">{{ scheme.name }}</option>
{% endfor %}

splite

<option value="">---------</option>
{% for module in modules %}
<option value="{{ module.pk }}">{{ module.name }}</option>
{% endfor %}